version: '3.3'
services:

  frontend:
    image: do1otov/foodgram-frontend:latest
    container_name: foodgram-front
    entrypoint: sh -c "cp -r /app/build/* /static/"
    volumes:
      - frontend_static:/static/

  backend:
    image: do1otov/foodgram-backend:latest
    restart: always
    container_name: foodgram-back
    env_file:
      - ./.env
    expose:
      - 8000
    volumes:
      - media_data:/app/media/
      - backend_static_data:/app/backend_static/
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: foodgram-db
    env_file:
      - ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  nginx:
    image: nginx:1.25.4-alpine
    container_name: foodgram-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_data:/static/
      - media_data:/media/
      - backend_static_data:/backend_static/
      - frontend_static:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend

volumes:
  pg_data:
  static_data:
  media_data:
  backend_static_data:
  frontend_static:
