# Generated by Django 5.2.1 on 2025-05-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_link_code',
            field=models.CharField(editable=False, max_length=6, unique=True, verbose_name='Код короткой ссылки'),
        ),
    ]
